import * as PIXI from 'pixi.js'

export function appendCloseups (properties, PIXIApp) {

  // console.log('Appended tag:', properties.title)

  // container for storing sprite, text etc. in
  const tagContainer = new PIXI.Container()
  tagContainer.name = properties.title
  tagContainer.x = Math.random() * 500 // currently mockup coordinates. TODO: generated by force layout
  tagContainer.y = Math.random() * 500

  // create container for each tag origin
  for (const [index, occurrence] of properties.occurrences.entries()) {
    
    // container to hold all occurrences of tag from iterated origin
    const occurrenceContainer = new PIXI.Container()

    // define positions in origin image
    const crop = new PIXI.Rectangle(
      occurrence.geometry[0].x,
      occurrence.geometry[0].y,
      occurrence.geometry[0].width,
      occurrence.geometry[0].width)
    
    // load origin image from PIXI loader
    const resource = PIXIApp.loader.resources[occurrence.origin]

    // create texture from crop of origin image
    const texture = new PIXI.Texture(resource.texture, crop)
    texture.updateUvs() // https://pixijs.download/dev/docs/PIXI.Texture.html#updateUvs
    
    // create sprite from texture
    let sprite = new PIXI.Sprite(texture)
    sprite.x = 0 // TODO: in Tag view these coordinates need to be generated from a force layout
    sprite.y = 0
    sprite.width = properties.tagCount * 20 // currently mockup dimensions TODO: generate from force layout
    sprite.height = properties.tagCount * 20

    sprite.visible = (index != 0) ? false : true // TODO: needs to be automated to display depictions from all origins

    // add interactivity
    sprite.interactive = true
    sprite.buttonMode = true

    // add events
    sprite.on('pointerover', (event) => {
      console.log('hover event', properties)
    })
    sprite.on('pointertap', (event) => {
      console.log('switching to Tag view', properties)
    })

    // texture swap ...

    // add sprite to occurrence container
    occurrenceContainer.addChild(sprite)
    tagContainer.addChild(occurrenceContainer)
  }

  // create text for tag title
  const textStyle = new PIXI.TextStyle({
      fontFamily: "\"Arial\", sans-serif",
      fontSize: 18,
      fontWeight: 400,
      dropShadow: false,
      dropShadowAngle: 0,
      dropShadowBlur: 5,
      dropShadowDistance: 2
  })
  const tagTitle = new PIXI.Text(properties.title + ' (' + properties.tagCount + ')', textStyle)
  tagContainer.addChild(tagTitle)
  
  // return container for appending to a parent
  return tagContainer
  
}